version: '3.4'

services:
  web:
    build: 
        context: ./Kubernetes
        dockerfile: Dockerfile        
    ports:
      - "5000:5000"
  reverseproxy:
    image: nginx:latest
    volumes:      
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "4000:4000"
      
